server:
  port: 8081

kafka-config:
  bootstrap-servers: 74.234.153.55:9092
  topic-name: gps-data-topic
  topic-names-to-create:
    - gps-data-topic


spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:D:\Amine\Desktop\projects\data-collection\kafka-sqllite-service\src\main\resources\gps.db

  jpa:
    database-platform: com.springboot.sqlite.SQLDialect
    hibernate:
      ddl-auto: update

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  consumer-group-id: gps-data-topic-consumer
  batch-listener: true
  auto-startup: true
  auto-offset-reset: earliest
  concurrency-level: 3
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-record: 500
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000